//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransForce.API.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_RPT_REG_CP_INSP_VIOL_DETAIL
    {
        public int ID { get; set; }
        public string TransID { get; set; }
        public string DOTNumber { get; set; }
        public Nullable<int> INSPECTION_ID { get; set; }
        public string VIOL_UNIT { get; set; }
        public string VIOL_CAT { get; set; }
        public string VIOL_OOS { get; set; }
        public string POST_CRASH_FL { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
