//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransForce.API.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_RPT_REG_CP_CRASH_ID
    {
        public int ID { get; set; }
        public string TransId { get; set; }
        public string DOTNumber { get; set; }
        public Nullable<int> RPT_REG_CP_CRASH_ID { get; set; }
        public string SEQ_OF_EVENT1 { get; set; }
        public string SEQ_OF_EVENT2 { get; set; }
        public string SEQ_OF_EVENT3 { get; set; }
        public string SEQ_OF_EVENT4 { get; set; }
        public string DRIVER_LAST_NAME { get; set; }
        public string DRIVER_FIRST_NAME { get; set; }
        public string DRIVER_MI { get; set; }
        public string TOW_AWAY { get; set; }
        public Nullable<System.DateTime> REPORT_DATE { get; set; }
        public string REPORT_TIME { get; set; }
        public string REPORT_NUMBER { get; set; }
        public string LOCATION { get; set; }
        public string COUNTY { get; set; }
        public string CITY1 { get; set; }
        public string STATE1 { get; set; }
        public Nullable<int> FATALITIES1 { get; set; }
        public Nullable<int> INJURIES { get; set; }
        public string HAZMAT_FLAG { get; set; }
        public string CARRIER_NAME { get; set; }
        public string CARRIER_CITY { get; set; }
        public string CARRIER_STATE { get; set; }
        public string VEH_LIC_NUMBER { get; set; }
        public string VEH_LIC_STATE { get; set; }
        public string DRIVER_LIC_NUMBER { get; set; }
        public string DRIVER_LIC_STATE { get; set; }
        public Nullable<System.DateTime> DRIVER_BDAY { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
