//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransForce.API.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_VIOL_CAT_TYPE_NAME
    {
        public int ID { get; set; }
        public string INSP_VIOLATION_CATEGORY_NAME1 { get; set; }
        public string INSP_VIOLATION_CATEGORY_DESC { get; set; }
        public Nullable<int> SEQ_ORDER1 { get; set; }
        public string DOTNumber { get; set; }
        public string TransId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
