//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransForce.API.Entitys
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TFPMEntities : DbContext
    {
        public TFPMEntities()
            : base("name=TFPMEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CustomerDOTNumber> CustomerDOTNumbers { get; set; }
        public virtual DbSet<CustomerProfile> CustomerProfiles { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<G_RPT_REG_CP_CRASH_ID> G_RPT_REG_CP_CRASH_ID { get; set; }
        public virtual DbSet<G_RPT_REG_CP_INSP_ID> G_RPT_REG_CP_INSP_ID { get; set; }
        public virtual DbSet<G_RPT_REG_CP_INSP_VIOL_DETAIL> G_RPT_REG_CP_INSP_VIOL_DETAIL { get; set; }
        public virtual DbSet<G_VIOL_CAT_TYPE_NAME> G_VIOL_CAT_TYPE_NAME { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Location_Configuration> Location_Configuration { get; set; }
        public virtual DbSet<LocationFieldType> LocationFieldTypes { get; set; }
        public virtual DbSet<LocationMetadata> LocationMetadatas { get; set; }
        public virtual DbSet<ManualRSI> ManualRSIs { get; set; }
    }
}
