//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransForce.Web.Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomerDOTNumber
    {
        public int ItemID { get; set; }
        public int CustomerID { get; set; }
        [Display(Name = "US DOT Number")]
        public string DOTNumber { get; set; }
        [Display(Name = "Tag")]
        public string DOTTag { get; set; }
        [Display(Name = "Active")]
        public bool IsActive { get; set; }

        public string DOTStaus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }

        public virtual CustomerProfile CustomerProfile { get; set; }
    }
}
