//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransForce.Web.Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Driver
    {
        [Display(Name ="DOT Number")]
        public int DriverID { get; set; }
        public int CompanyId { get; set; }
        public string DOTNumber { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string LicenseState { get; set; }
        public string LicenseNumber { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM-dd-yy}")]
        public System.DateTime DOB { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string MI { get; set; }
        public Nullable<bool> isDelete { get; set; }

        public virtual CustomerProfile CustomerProfile { get; set; }
    }
}
