//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransForce.Web.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationMetadata
    {
        public int LocMID { get; set; }
        public int CustomerID { get; set; }
        public int LocConfigID { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public string FieldType { get; set; }
        public string Tags { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual CustomerProfile CustomerProfile { get; set; }
        public virtual Location_Configuration Location_Configuration { get; set; }
    }
}
